baseURL = "/"
languageCode = "en-us"
title = "Resume | UPENDRA UPADHYAY"
disableKinds = ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme = "resume-A4"

[params]
useFontAwesome = true
avatar = "avatar.jpg"
bib_style = "IEEE" # IEEE, APA, else

[params.display]
experience = true
education = true
languages = false
awards = true
skills = false
skills_grouped = true
interests = true
contact = true
linkedin = true
github = true
codepen = true
facebook = true
tagline = false
aboutMe = false
projects = true
publications = false
certificates =false
avatar = false

[params.title_as]
experience = "Experience"
education = "Education"
languages = "Languages"
awards = "Achievements"
skills = "Skills"
certificates = "Certifications"
interests = "Interests"
about_me = "About Me"
publications = "Publications"
projects = "Projects"

[params.display.footer]
footer = true
links = true
credits = false

[params.footer]
footnote = "You can print this resume in A4 size or save as pdf."

[params.footer.links]
[[params.footer.links.link]]
prefix = "Contact me on"
name = "Linkedin"
url = "https://linkedin.com/in/upendra-upadhyay/"
icon = "fab fa-linkedin"

[[params.footer.links.link]]
prefix = "Check out my"
name = "Website"
url = "https://upendra1997.github.io"
icon = "fas fa-globe"
