baseURL: "resume"
languageCode: "en-us"
title: "Resume | UPENDRA UPADHYAY"
disableKinds: ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme: "resume-A4"


# Construct main column, side column and additional page from features
# Every column and page may include any features. Some features are
# created using generic widgets and you can add easily new features,
# as long as an existing widget can render it as you like.
#
# Common keys:
#   feature: name of the feature. For generic features, this is also the root key in the yaml file.
#   title: string rendered as the header of the element. Can be disabled with an empty string.
#   collection: the base name of the yaml file containing the data. Defaults to "features".
#   widget: `layout/partials/section-<widget>.html` used to render this element.
#
# Common widgets:
#
#   details-list:
#     Used by default, if section-<feature>.html doesn't exists.
#
#     Expects data in format (in yaml file):
#       title: the title string
#       subtitle: string rendered under title. E.g., company for projects, certificate authority etc.
#       date: date string, e.g., when a certificate was given
#       details: a text in markdown.
#       link: url where the title will link to
#       links: list of links rendered as a bullet list below details
#         prefix: a string before the link
#         title: a string inside the link
#         url: the destination of the link
#         icon: the icon string, e.g., "fas fa-cloud". rendered inside link and after title.
#
#   word-list:
#     Handy for skills and interests etc.
#
#     Additional keys:
#       style: Rendering style for word list. One of: list, compact, or title-list
#
#     Expects data in format (in yaml file):
#       A list of strings, if style is "list", or
#
#       A list of:
#         groupName: title of the group
#         list: list of strings rendered under the group

params:
  useFontAwesome: true
  css:
    - custom.scss
  header:
    # avatar: "avatar.jpg"
    contact: true
    tagline: false
    links: true
  side:
    - feature: education
    - feature: awards
      title: Achievements
    # - feature: languages
    - feature: skills
      widget: word-list
      style: compact # list, compact, title-list
    - feature: interests
      widget: word-list
      style: list
  pages:
    - features:
        # - feature: about
        #   title: About Me
        - feature: experience
        - feature: projects
          collection: projects
    # - features:
    #     - feature: publications
    #       style: IEEE # IEEE, APA, else
    #     - feature: awards
    #       title: Achievements
    #     - feature: certificates
    #       title: Certifications
    #     - feature: interests
    #       widget: word-list
    #       style: list

  footer:
    show: true
    credits: false
    footnote: >-
      You can print this resume in A4 size or save as pdf.
      {{< youtube w7Ft2ymGmfc >}}
    links:
      - prefix: Contact me on
        title: Linkedin
        url: "https://linkedin.com/in/upendra-upadhyay/"
        icon: "fab fa-linkedin"
      - prefix: Check out my
        title: Website
        url: "https://upendra1997.github.io"
        icon: fas fa-globe

# [params.display]
# experience: true
# education: true
# languages: false
# awards: true
# skills: false
# skills_grouped: true
# interests: true
# linkedin: true
# github: true
# codepen: true
# facebook: true
# aboutMe: false
# projects: true
# publications: false
# certificates:false
# avatar: false

# [params.title_as]
# experience: "Experience"
# education: "Education"
# languages: "Languages"
# awards: "Achievements"
# skills: "Skills"
# certificates: "Certifications"
# interests: "Interests"
# about_me: "About Me"
# publications: "Publications"
# projects: "Projects"

# [params.display.footer]
# footer: true
# links: true
# credits: false

# [params.footer]
# footnote: "You can print this resume in A4 size or save as pdf."

# [params.footer.links]
# [[params.footer.links.link]]
# prefix: "Contact me on"
# name: "Linkedin"
# url: "https://linkedin.com/in/upendra-upadhyay/"
# icon: "fab fa-linkedin"

# [[params.footer.links.link]]
# prefix: "Check out my"
# name: "Website"
# icon: "fas fa-globe"
